### ISSUE TITLE
Workouts Resource

### ISSUE THREAD

**Issue by lestece** [lestece/fitU-API#3]
The API allows us to retrieve a list of all the workouts or a single workout by id. A user can create a workout and update or delete a workout owned.  

## Tasks:
- [ ] Write the WorkoutList view with the GET and POST method
- [ ] Write the WorkoutSerializer class
- [ ] Create a WorkoutDetail view with GET, POST and DELETE methods
